import { SlotSkin } from '../../../../types';

export const slotFaraonSkin: SlotSkin = {
  id: 'slot-faraon',
  name: 'El Faraón del Nilo',
  title: 'El Faraón del Nilo',
  subtitle: 'Tesoros de las Pirámides & Riquezas Ocultas',
  category: 'slots',
  themeColor: '#d4af37',
  accentColor: '#f3e5ab',
  gradientBackground: 'from-[#1a1205] via-[#2a1d08] to-[#120c03]',
  cardBorder: 'border-[#d4af37]/50',
  reelsCount: 5,
  rowsCount: 3,
  soundProfile: {
    ambientTrack: 'mystic_desert_harp',
    spinKey: 'egypt_stone_roll',
    winKey: 'golden_scarab_chime',
    jackpotKey: 'anubis_triumph_fanfare',
  },
  features: [
    'Wild Escarabajo Dorado',
    'Scatter Pirámide Imperial (hasta 25 Giros Libres)',
    'Multiplicador Dinastía x10',
    'Jackpot Ojo de Horus',
  ],
  symbols: [
    {
      id: 'faraon_oro',
      name: 'Máscara del Faraón',
      label: 'FARAÓN',
      emoji: '👑',
      color: '#ffd700',
      payouts: { 3: 50, 4: 250, 5: 1000 },
      isJackpot: true,
      badge: 'JACKPOT 1000x',
    },
    {
      id: 'escarabajo_wild',
      name: 'Escarabajo Sagrado (WILD)',
      label: 'WILD',
      emoji: '🪲',
      color: '#00e5ff',
      payouts: { 3: 30, 4: 150, 5: 500 },
      isWild: true,
      badge: 'SUSTITUYE',
    },
    {
      id: 'piramide_scatter',
      name: 'Pirámide de Guiza (SCATTER)',
      label: 'SCATTER',
      emoji: '🔺',
      color: '#ff9100',
      payouts: { 3: 20, 4: 100, 5: 300 },
      isScatter: true,
      badge: 'GIROS GRATIS',
    },
    {
      id: 'ojo_horus',
      name: 'Ojo de Horus',
      label: 'HORUS',
      emoji: '👁️',
      color: '#2979ff',
      payouts: { 3: 15, 4: 60, 5: 200 },
    },
    {
      id: 'anubis',
      name: 'Chacal de Anubis',
      label: 'ANUBIS',
      emoji: '🐺',
      color: '#b388ff',
      payouts: { 3: 10, 4: 40, 5: 150 },
    },
    {
      id: 'cruz_anj',
      name: 'Cruz de Anj',
      label: 'ANJ',
      emoji: '☥',
      color: '#e040fb',
      payouts: { 3: 8, 4: 30, 5: 100 },
    },
    {
      id: 'vaso_canopo',
      name: 'Vaso Canopo',
      label: 'ÁMFORA',
      emoji: '🏺',
      color: '#ffab40',
      payouts: { 3: 5, 4: 20, 5: 75 },
    },
    {
      id: 'pergamino',
      name: 'Papiro Sagrado',
      label: 'PAPIRO',
      emoji: '📜',
      color: '#c5cae9',
      payouts: { 3: 4, 4: 15, 5: 50 },
    },
  ],
};
