import { SlotSkin } from '../../../../types';

export const slotGauchoDeOroSkin: SlotSkin = {
  id: 'slot-gaucho-de-oro',
  name: 'El Gaucho de Oro',
  title: 'El Gaucho de Oro Megaways™',
  subtitle: 'La Aventura Legendaria en el Corazón de la Pampa',
  category: 'slots',
  themeColor: '#c5a059',
  accentColor: '#fae5b8',
  gradientBackground: 'from-[#0b1424] via-[#142340] to-[#080d1a]',
  cardBorder: 'border-[#c5a059]/60',
  reelsCount: 5,
  rowsCount: 3,
  soundProfile: {
    ambientTrack: 'criollo_guitar_chacarera',
    spinKey: 'spurs_jingling',
    winKey: 'gaucho_sapucay_cheer',
    jackpotKey: 'gran_pozo_pampa_fanfare',
  },
  features: [
    'Boleadoras Wild Multiplicador',
    'Bono Pampa Dorada',
    'Cascadas de Fichas Argentinas',
    'Jackpot Gran Federal',
  ],
  symbols: [
    {
      id: 'gaucho_oro',
      name: 'Gaucho de Oro (WILD)',
      label: 'EL GAUCHO',
      emoji: '🤠',
      color: '#ffd700',
      payouts: { 3: 100, 4: 500, 5: 2500 },
      isWild: true,
      isJackpot: true,
      badge: 'JACKPOT FEDERAL',
    },
    {
      id: 'caballo_criollo',
      name: 'Caballo Criollo',
      label: 'CABALLO',
      emoji: '🐎',
      color: '#ffb74d',
      payouts: { 3: 40, 4: 180, 5: 750 },
    },
    {
      id: 'sol_argentino',
      name: 'Sol de Mayo (SCATTER)',
      label: 'SOL MAYO',
      emoji: '☀️',
      color: '#ffe082',
      payouts: { 3: 25, 4: 120, 5: 450 },
      isScatter: true,
      badge: 'GIROS PAMPA',
    },
    {
      id: 'facon_plata',
      name: 'Facón de Plata Grabada',
      label: 'FACÓN',
      emoji: '🗡️',
      color: '#90caf9',
      payouts: { 3: 20, 4: 80, 5: 300 },
    },
    {
      id: 'mate_calabaza',
      name: 'Mate Imperial de Plata',
      label: 'MATE',
      emoji: '🧉',
      color: '#a5d6a7',
      payouts: { 3: 15, 4: 50, 5: 200 },
    },
    {
      id: 'boleadoras',
      name: 'Boleadoras de Cuero',
      label: 'BOLEADORAS',
      emoji: '🎯',
      color: '#ce93d8',
      payouts: { 3: 10, 4: 35, 5: 140 },
    },
    {
      id: 'guitarra_criolla',
      name: 'Guitarra Criolla',
      label: 'GUITARRA',
      emoji: '🎸',
      color: '#ffcc80',
      payouts: { 3: 6, 4: 20, 5: 80 },
    },
  ],
};
