import { SlotSkin } from '../../../../types';

export const slotCleopatraSkin: SlotSkin = {
  id: 'slot-cleopatra',
  name: 'Cleopatra Reina del Nilo',
  title: 'Cleopatra Reina del Nilo',
  subtitle: 'Seducción, Joyas Reales y Pozos Legendarios',
  category: 'slots',
  themeColor: '#e0a96d',
  accentColor: '#ffe5b4',
  gradientBackground: 'from-[#1f0d24] via-[#2f1338] to-[#140618]',
  cardBorder: 'border-[#e0a96d]/60',
  reelsCount: 5,
  rowsCount: 3,
  soundProfile: {
    ambientTrack: 'oriental_cleopatra_sitar',
    spinKey: 'silk_wheel_spin',
    winKey: 'cleopatra_jewel_sparkle',
    jackpotKey: 'queen_fanfare_hymn',
  },
  features: [
    'Cleopatra Wild Multiplicador Doble x2',
    'Bono Esfinge de Oro',
    '15 Giros Libres con Todos los Premios Triplicados (x3)',
    'Retiro Instantáneo de Fichas',
  ],
  symbols: [
    {
      id: 'cleopatra_queen',
      name: 'Reina Cleopatra (WILD)',
      label: 'CLEOPATRA',
      emoji: '👸',
      color: '#ff4081',
      payouts: { 3: 100, 4: 500, 5: 2000 },
      isWild: true,
      isJackpot: true,
      badge: 'WILD x2',
    },
    {
      id: 'esfinge_scatter',
      name: 'Esfinge Imperial (SCATTER)',
      label: 'ESFINGE',
      emoji: '🗿',
      color: '#ffd700',
      payouts: { 3: 25, 4: 120, 5: 400 },
      isScatter: true,
      badge: 'BONO x3',
    },
    {
      id: 'loto_dorado',
      name: 'Flor de Loto Real',
      label: 'LOTO',
      emoji: '🪷',
      color: '#f48fb1',
      payouts: { 3: 20, 4: 80, 5: 250 },
    },
    {
      id: 'cetro_real',
      name: 'Cetro de la Reina',
      label: 'CETRO',
      emoji: '🪄',
      color: '#ffd54f',
      payouts: { 3: 15, 4: 50, 5: 180 },
    },
    {
      id: 'espejo_bronce',
      name: 'Espejo de Bronce Pulido',
      label: 'ESPEJO',
      emoji: '🪞',
      color: '#80cbc4',
      payouts: { 3: 10, 4: 35, 5: 120 },
    },
    {
      id: 'abanico_plumas',
      name: 'Abanico Real',
      label: 'ABANICO',
      emoji: '🪶',
      color: '#90caf9',
      payouts: { 3: 8, 4: 25, 5: 90 },
    },
    {
      id: 'collar_zafiros',
      name: 'Collar de Zafiros',
      label: 'ZAFIRO',
      emoji: '💎',
      color: '#00e676',
      payouts: { 3: 5, 4: 18, 5: 60 },
    },
  ],
};
