import { SlotSkin } from '../../../../types';

export const slotSolDeMayoSkin: SlotSkin = {
  id: 'slot-sol-de-mayo',
  name: 'Sol de Mayo Jackpot 777',
  title: 'Sol de Mayo Jackpot 777',
  subtitle: 'Edición Triple Respin & Campanas Doradas',
  category: 'slots',
  themeColor: '#ffb300',
  accentColor: '#fff8e1',
  gradientBackground: 'from-[#1e1302] via-[#2f1f05] to-[#120a00]',
  cardBorder: 'border-[#ffb300]/60',
  reelsCount: 5,
  rowsCount: 3,
  soundProfile: {
    ambientTrack: 'las_vegas_classic_casino_murmur',
    spinKey: 'mechanical_777_reels',
    winKey: 'bell_strike_ringing',
    jackpotKey: 'siren_jackpot_celebration',
  },
  features: [
    'Triple 777 Imperial con Multiplicador x7',
    'Hold & Win Sol Dorado',
    'Campanas de Oro Argentino',
    'Pozo Acumulado Millonario',
  ],
  symbols: [
    {
      id: 'triple_seven',
      name: 'Triple 777 Dorado',
      label: '777 GOLD',
      emoji: '🎰',
      color: '#ffd700',
      payouts: { 3: 150, 4: 750, 5: 3000 },
      isJackpot: true,
      badge: 'JACKPOT x3000',
    },
    {
      id: 'sol_dorado_wild',
      name: 'Sol de Mayo (WILD)',
      label: 'SOL MAYO',
      emoji: '🌞',
      color: '#ffa000',
      payouts: { 3: 50, 4: 250, 5: 1000 },
      isWild: true,
      badge: 'WILD TOTAL',
    },
    {
      id: 'estrella_scatter',
      name: 'Estrella Platina (SCATTER)',
      label: 'ESTRELLA',
      emoji: '⭐',
      color: '#e0e0e0',
      payouts: { 3: 30, 4: 150, 5: 500 },
      isScatter: true,
      badge: 'RESPIN',
    },
    {
      id: 'campana_oro',
      name: 'Campana Dorada',
      label: 'CAMPANA',
      emoji: '🔔',
      color: '#ffca28',
      payouts: { 3: 20, 4: 90, 5: 350 },
    },
    {
      id: 'diamante_azul',
      name: 'Diamante Imperial',
      label: 'DIAMANTE',
      emoji: '💎',
      color: '#4fc3f7',
      payouts: { 3: 15, 4: 60, 5: 250 },
    },
    {
      id: 'bar_triple',
      name: 'BAR Triple',
      label: 'BAR',
      emoji: '🍫',
      color: '#ef5350',
      payouts: { 3: 10, 4: 40, 5: 160 },
    },
    {
      id: 'cerezas_rojas',
      name: 'Cerezas de la Suerte',
      label: 'CEREZAS',
      emoji: '🍒',
      color: '#e91e63',
      payouts: { 3: 5, 4: 20, 5: 75 },
    },
  ],
};
