import { SlotSkin } from '../../../../types';

export const slotDuendesSkin: SlotSkin = {
  id: 'slot-duendes',
  name: 'Duendes de la Fortuna',
  title: 'Duendes de la Fortuna',
  subtitle: 'La Olla de Oro al Final del Arcoíris Criollo',
  category: 'slots',
  themeColor: '#00c853',
  accentColor: '#b9f6ca',
  gradientBackground: 'from-[#031d0b] via-[#092d14] to-[#021407]',
  cardBorder: 'border-[#00e676]/50',
  reelsCount: 5,
  rowsCount: 3,
  soundProfile: {
    ambientTrack: 'celtic_irish_flute_jig',
    spinKey: 'clover_reel_tumble',
    winKey: 'gold_coins_showering',
    jackpotKey: 'leprechaun_laugh_jackpot',
  },
  features: [
    'Wild Duende Pícaro con Respin',
    'Olla de Oro con Multiplicadores Explosivos',
    'Scatter Arcoíris Mágico',
    'Mini-juego Selección de Tréboles',
  ],
  symbols: [
    {
      id: 'duende_wild',
      name: 'Duende de la Fortuna (WILD)',
      label: 'DUENDE',
      emoji: '🧝',
      color: '#00e676',
      payouts: { 3: 80, 4: 400, 5: 1500 },
      isWild: true,
      isJackpot: true,
      badge: 'WILD EXPANSIVO',
    },
    {
      id: 'olla_oro',
      name: 'Olla de Monedas de Oro',
      label: 'OLLA DE ORO',
      emoji: '🏺',
      color: '#ffd700',
      payouts: { 3: 40, 4: 200, 5: 800 },
      badge: 'GRAN PREMIO',
    },
    {
      id: 'arcoiris_scatter',
      name: 'Arcoíris Encantado (SCATTER)',
      label: 'ARCOÍRIS',
      emoji: '🌈',
      color: '#ff4081',
      payouts: { 3: 20, 4: 100, 5: 350 },
      isScatter: true,
      badge: 'GIROS MÁGICOS',
    },
    {
      id: 'trebol_4_hojas',
      name: 'Trébol de 4 Hojas',
      label: 'TRÉBOL',
      emoji: '🍀',
      color: '#69f0ae',
      payouts: { 3: 15, 4: 60, 5: 220 },
    },
    {
      id: 'herradura_dorada',
      name: 'Herradura de la Suerte',
      label: 'HERRADURA',
      emoji: '🧲',
      color: '#ffd54f',
      payouts: { 3: 12, 4: 45, 5: 160 },
    },
    {
      id: 'sombrero_verde',
      name: 'Sombrero Mágico',
      label: 'SOMBRERO',
      emoji: '🎩',
      color: '#00b0ff',
      payouts: { 3: 10, 4: 35, 5: 120 },
    },
    {
      id: 'jarra_cerveza',
      name: 'Pinta Artesanal',
      label: 'PINTA',
      emoji: '🍺',
      color: '#ffab40',
      payouts: { 3: 6, 4: 20, 5: 80 },
    },
    {
      id: 'pipa_roble',
      name: 'Pipa de Roble',
      label: 'PIPA',
      emoji: '🪵',
      color: '#d7ccc8',
      payouts: { 3: 4, 4: 15, 5: 50 },
    },
  ],
};
